### ISSUE TITLE
Modo 12 to Blender, import error.

### ISSUE THREAD

**Issue by SonKim** [ksons/gltf-blender-importer#16]
I'm saving the .glb file from Modo 12 and trying to get a simple cube into Blender 2.79.1. Upon importing I get the following errors(see attachment) ,the cube.glb is also attached in the zip.

[CubeTest.zip](https://github.com/ksons/gltf-blender-importer/files/1822814/CubeTest.zip)

![gltf_import_error](https://user-images.githubusercontent.com/7035871/37567574-08604288-2a86-11e8-8066-00683fdd4c2e.jpg)

**Comment by scurest** [comment]
Confirmed. It happens when you import when not in object mode. We can just switch to object mode before we create the armature. Possible patch

```patch
diff --git a/addons/io_scene_gltf/node.py b/addons/io_scene_gltf/node.py
index 9de3b9e..0f65e5a 100644
--- a/addons/io_scene_gltf/node.py
+++ b/addons/io_scene_gltf/node.py
@@ -126,6 +126,12 @@ def find_root_idxs(op):
 
 
 def generate_armature_object(op):
+    try:
+        bpy.ops.object.mode_set(mode='OBJECT', toggle=True)
+    except RuntimeError:
+        # Ignore the error from already being in object mode
+        pass
+
     bpy.ops.object.add(type='ARMATURE', enter_editmode=True)
     arma_ob = bpy.context.object
     arma_ob.name = 'Node Forest'
```

**Comment by SonKim** [comment]
Yup,switching to object before importing works, thank you!!
