### ISSUE TITLE
Importing creates armature, normal?

### ISSUE THREAD

**Issue by SonKim** [ksons/gltf-blender-importer#17]
So i'm just importing a cube with no material or bones, but the importer creates an armature upon importing, is that normal? If so, it would be nice if it doesn't create an armature.

[CubeSample.zip](https://github.com/ksons/gltf-blender-importer/files/1823700/CubeSample.zip)

**Comment by scurest** [comment]
That's normal. I made it import all nodes as armature bones. The reasoning was basically

1. In glTF, all nodes are homogenous (ie. there are not different "types" of nodes). Therefore I wanted all the nodes to be of the same type when imported into Blender.
2. In glTF, meshes are skinned based on the transforms of nodes. In Blender, a mesh can only be skinned based on the pose of an armature bone.
3. Therefore, I imported every glTF node as an armature bone.

But this has never worked out very well so I'd be more than happy for someone to replace the whole node importer with something better.

In the meantime, it's easy to rip out the armature stuff and replace the bones with Blender objects. I pushed an [`empties`](https://github.com/scurest/gltf-blender-importer/tree/empties) branch to my repo that does that if you want to try it. Note that it removes skinning support though.
