### ISSUE TITLE
Broken in Blender 2.80.5

### ISSUE THREAD

**Issue by SonKim** [ksons/gltf-blender-importer#21]
I just updated to .3 version it works great for 2.79! and decided to try it on Blender 2.80.5, I get an error(see attach image). 

![error](https://user-images.githubusercontent.com/7035871/37814681-7952bf20-2e28-11e8-8462-0abad37e1012.jpg)

**Comment by scurest** [comment]
There's now Blender 2.8 support on the [blender-2.8](https://github.com/ksons/gltf-blender-importer/tree/blender-2.8) branch.

I've checked this and in my build of 2.8 from October 8, `scene.render.engine` is valid again. I did find another issue nearby in the code though so it was a good thing anyway :)
