### ISSUE TITLE
gltf 2.0 sample model BoxVertexColors doesn't import with vertex colors

### ISSUE THREAD

**Issue by garyo** [ksons/gltf-blender-importer#23]
Importing that model using the gltf-blender-importer 0.3.0 imports the cube, but no vertex colors are visible in the render. It does have a default metallicRoughnessPBR surface, so I'm not sure why the vertex colors don't show up.

**Comment by scurest** [comment]
There's an input slot on the metallicRoughnessPBR for vertex color, but I never attached it to anything. IIRC the reason was that the material needs to work with both meshes that have and meshes that don't have vertex colors and I couldn't figure out how to do that (slotting in an "Attribute" node for a non-existent attribute seems to produce a solid red color).

**Comment by garyo** [comment]
Shouldn't a material multiply the (interpolated) per-vertex colors with the material's albedo? 

I wasn't sure from your reply whether this is something I as a user could do, or if it's something that needs to be added to the importer or something that should be improved in Blender core. (I'm no Blender expert, pretty much a newbie.)

**Comment by scurest** [comment]
Sure, you can do it. In the Nodes Editor, add an attribute node that feeds the "COLOR_0" layer into the "Vertex Color" slot for the metallicRoughnessPBR node (indicated with the red arrow here).

![nodes](https://user-images.githubusercontent.com/11024420/38688051-c2a4ae98-3e3d-11e8-9676-a388e8894d5e.png)

**Comment by garyo** [comment]
Thanks -- that works fine. Is there a way to automate this? I'm importing big glTF models and don't want to have to hook things up by hand.

**Comment by scurest** [comment]
You can patch `material.py` by adding

````py

    vert_color_node = tree.nodes.new('ShaderNodeAttribute')
    vert_color_node.location = -150, -300
    vert_color_node.attribute_name = 'COLOR_0'
    links.new(vert_color_node.outputs['Color'], group_node.inputs['Vertex Color'])
````

around [here](https://github.com/ksons/gltf-blender-importer/blob/b154ca9dd98f776a95cc40a27080099e2ba12663/addons/io_scene_gltf/material.py#L232).

Keep in mind what I said about it not working if the material is applied to a mesh without vertex colors. It also won't work correctly with multiple color layers (eg `COLOR_1`).
