### ISSUE TITLE
Animation doesn't seem to be working, or maybe I have to do something to use it

### ISSUE THREAD

**Issue by garyo** [ksons/gltf-blender-importer#25]
I tried the animation glTF samples, e.g. AnimatedTriangle. When it's imported, I don't see any animation on the triangle's rotation (as specified in the glTF file) or any keyframes in the graph editor. I see in the import code it's doing _something_ with the animation, I just don't know how to get that to actually animate.

**Comment by garyo** [comment]
Perhaps I can help implement it - it's an important feature for me. I don't know the Blender API hardly at all, but I did just write a glTF exporter. Do you know a good resource to start with the Blender API?

**Comment by julienduroure** [comment]
Hello guys,

I am working on another glTF 2.0 importer implementation for one of my client,  where animations (objects / ShapeKeys / Rigs) should work : 

https://github.com/julienduroure/gltf2-blender-importer

Please have a look on it :)

**Comment by scurest** [comment]
There is some animation loading working on my [dev](https://github.com/scurest/gltf-blender-importer/tree/dev) branch.

**Comment by zakria257** [comment]
Hi!
How to add keyframes to fluid simulation in blender so that it can be imported to Unity to work smoothly? @garyo @scurest

**Comment by scurest** [comment]
Animation support is in the latest release; just tick the "Import Animations" box when you import. There's some support for the EXT_property_animation extension too.

An animation is imported as a set of actions, one for each object, named like `animation name@object name`. The first animation plays by default. You can switch what action is played on a object through the Action Editor in the Dope Sheet.
