### ISSUE TITLE
Store vertex color alpha into a second color attribute

### ISSUE THREAD

**Issue by my2iu** [ksons/gltf-blender-importer#26]
It's possible that I don't fully understand Blender, but it's my understanding that gltf lets you store vertex colors in RGBA format while Blender only accepts vertex colors in RGB format. So the importer ends up discarding the extra alpha values of the vertex colors in a gltf file. Is it possible to stash those alpha values into a second vertex color attribute during import? So the importer would create a COLOR_0 and a ALPHA_0/COLOR_0_ALPHA or something like that.

**Comment by ksons** [comment]
Blender switches from RGB to RGBA vertex colors somewhere between 2.79.0 and 2.79.4. Code on master / next release will cover for that.
