### ISSUE TITLE
please add  import Scale parm

### ISSUE THREAD

**Issue by sonygod** [ksons/gltf-blender-importer#28]
please add  import global scale   when import glb

**Comment by sonygod** [comment]
add KHR_texture_transform support?

**Comment by scurest** [comment]
KHR_texture_transform should be supported in v0.4.

**Comment by scurest** [comment]
Global scale is an import option in v0.5.0.

![units](https://user-images.githubusercontent.com/11024420/52534243-d0571d80-2d04-11e9-9212-9c2c80c28b92.png)
