### ISSUE TITLE
Vertex Groups

### ISSUE THREAD

**Issue by Blenux** [ksons/gltf-blender-importer#33]
Hey just wondering if vertex groups supported with this importer?, loaded in a animation but no vertex groups on the mesh.

**Comment by scurest** [comment]
They work in current master

![groups](https://user-images.githubusercontent.com/11024420/43995080-5dd355a2-9d6d-11e8-8982-16fe46e1976e.png)

**Comment by scurest** [comment]
Support for this has made it into the latest release!
