### ISSUE TITLE
installing Blender UI Preferences unzips wrong folder

### ISSUE THREAD

**Issue by stevensanborn** [ksons/gltf-blender-importer#42]
unzips gltf-blender-importer-master folder in add ons folder instead of io_scene_gltf

**Comment by scurest** [comment]
I think you are trying to install an archive of the whole repo, eg. from the "Clone or Download" button on Github's UI or from a "Source Code" link on the Releases page.

You should be installing the archive from the download (⇩) link on the readme: ie. [this](https://github.com/ksons/gltf-blender-importer/releases/download/v0.4.0/io_scene_gltf-0.4.0.zip).
