### ISSUE TITLE
Feature request: importing a gltf+bin

### ISSUE THREAD

**Issue by schiette** [ksons/gltf-blender-importer#47]
I've been trying to import a gltf+bin file but had no success. When I convert the file to glb it works fine. 

Does the importer not support gltf+bin? If so, any chance this can be added?

**Comment by scurest** [comment]
gltf+bin should work fine. Lots of the test files are gltf+bin. What's the error?

Note that I'm not really working on this anymore since an official glTF addon was added to Blender 2.8.

**Comment by schiette** [comment]
Hey Scurest

I'm so sorry. I thought this project was part of 2.8.  I'll report this on the blender dev. pages instead.
