### ISSUE TITLE
Float error

### ISSUE THREAD

**Issue by rzimin** [ksons/gltf-blender-importer#49]
Hello, 
getting error for this line about TypeError: 'float' object is not subscriptable
mesh.py: 287
weight = weight_set[pidx][j]

[A320_NEO_LOD01.zip](https://github.com/ksons/gltf-blender-importer/files/5112921/A320_NEO_LOD01.zip)

**Comment by scurest** [comment]
You should use the glTF importer that ships with Blender. It has been better than this one since the Blender 2.83 release.

**Comment by rzimin** [comment]
I know, but that one does not work at all as it requires MSFT_texture_dds extension. This is how I ended up with your solution.
I fixed a dew issues, but cannot overcome this one.

I can comment the whole block, but getting weird results.

**Comment by scurest** [comment]
It would be easier for me to give you a patch of the official importer that implements MSFT_texture_dds (IIRC it was trivial to implement). Would that be okay? I haven't looked at this repo in quite a while.

**Comment by rzimin** [comment]
That would probably work... official one throws me some assetion errors on import, but I believe this is all about that dds

**Comment by scurest** [comment]
You didn't include A320_NEO_LOD01.bin in your .zip so I can't test your file, but try this branch: [`dds`](https://github.com/scurest/glTF-Blender-IO/tree/dds).

btw this is on top of glTF-Blender-IO's master, which requires at least Blender 2.90, so make sure you have that.

**Comment by rzimin** [comment]
Still no good for me. Imports the bones and throws an error.
Uploaded full package with different LOD
[A320_NEO_LOD00.zip](https://github.com/ksons/gltf-blender-importer/files/5113102/A320_NEO_LOD00.zip)

**Comment by scurest** [comment]
It errors because your file has a NORMAL accessor that is a VEC4. Normals have to be VEC3.

Make sure your file passes the validator first. You should also use a simpler file for a testcase.

**Comment by scurest** [comment]
Here's a CesiumMan that uses a .dds texture for testing: [CesiumManDDS.zip](https://github.com/ksons/gltf-blender-importer/files/5113411/CesiumManDDS.zip)

**Comment by rzimin** [comment]
Thank you for your efforts. I see it is working and would be a great help moving on.
Unfortunately it did not worked for my case, as it seems the models I need to work on are not following glTF standards.

Anyway, thank you for your help!
