### ISSUE TITLE
Sketchfab imports are broken

### ISSUE THREAD

**Issue by Dummiesman** [ksons/gltf-blender-importer#9]
Any downloaded sketchfab GLTF won't import correctly. It's a mess of triangles
![image](https://user-images.githubusercontent.com/10748421/34287483-76a15d46-e6b5-11e7-8e11-bd63ad789f27.png)

**Comment by Vuzin** [comment]
I have this problem as well, any file from sketchfab turns out as a mess of triangles.

**Comment by ksons** [comment]
This is fixed in [v0.3.0](https://github.com/ksons/gltf-blender-importer/releases/tag/v0.3.0)
